### PR TITLE
Update to version 8.0.0

### PR DESCRIPTION
**Pull request by awvwgk**
Checklist
* [x] Used a fork of the feedstock to propose changes
* ~~Bumped the build number (if the version is unchanged)~~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by awvwgk** [comment]
@andreyz4k Happy to help co-maintain this package.

**Comment by awvwgk** [comment]
@conda-forge/core

**Comment by ocefpaf** [comment]
> @conda-forge/core

We usually wait ~1 week for the maintainer (@andreyz4k) to respond. If they don't then we merge it.
We have some exceptions for known MIA maintainers but I don't know if that is the case here.

**Comment by awvwgk** [comment]
There seems to be no activity on conda-forge since 2019 from the maintainer. But there is no urgency from my side.

**Comment by ocefpaf** [comment]
Indeed. There are quite a few open PRs. Thanks for taking on this feedstock!

**Pull request merged**
